-- Add total_letters_generated column
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS total_letters_generated INT DEFAULT 0;

COMMENT ON COLUMN profiles.total_letters_generated IS 'Total life-time letters generated by the user';

-- Update function to increment this counter (if there is one) or we handle it in API.
-- Ideally we might want a trigger or update the atomic function to handle this too.

CREATE OR REPLACE FUNCTION increment_total_letters(p_user_id UUID)
RETURNS VOID AS $$
BEGIN
  UPDATE profiles
  SET total_letters_generated = COALESCE(total_letters_generated, 0) + 1
  WHERE id = p_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION increment_total_letters TO authenticated;
GRANT EXECUTE ON FUNCTION increment_total_letters TO service_role;
