/*
  Migration: 014_schema_alignment
  Description: Aligns the live Supabase schema with the repository by adding missing columns 
               and standardizing the subscription tracking fields.
*/

-- 1. Add missing columns to profiles table
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS total_letters_generated INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_licensed_attorney BOOLEAN DEFAULT FALSE;

COMMENT ON COLUMN public.profiles.total_letters_generated IS 'Total life-time letters generated by the user';
COMMENT ON COLUMN public.profiles.is_licensed_attorney IS 'Indicates if the user is a licensed attorney maintained by admin';

-- 2. Standardize subscriptions table
-- Ensure remaining_letters and credits_remaining exist (they should, but for safety)
ALTER TABLE public.subscriptions 
ADD COLUMN IF NOT EXISTS remaining_letters INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS credits_remaining INT DEFAULT 0;

-- 3. Cleanup: Remove is_super_user if it somehow still exists (already dropped in migration 011)
ALTER TABLE public.profiles DROP COLUMN IF EXISTS is_super_user;

-- 4. Add missing indexes for performance (from scripts/001_setup_schema.sql)
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(email);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON public.subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_letters_user_id ON public.letters(user_id);
